# Generated by Django 5.1.1 on 2024-09-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comentarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topico",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tema", models.CharField(max_length=30)),
                ("foto", models.ImageField(upload_to="")),
                ("conteudo", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
