# Generated by Django 5.1.1 on 2024-09-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topico",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
